### ISSUE TITLE
ERROR: Failed to fetch macOS "Big-sur" recovery image with board id "Mac-2BD1B31983FE1663"!

### ISSUE THREAD

**Issue by wronglylightcig** [dockur/macos#85]
### Operating system

Debian 12

### Description

While downloading the image, it always gives 'Lost Connection' after few minutes, restart it will always make it works again, but it will end up the same. In Portainer, the IP-Adress and Published Ports just gone, it would come up after a restart, but it will also end up gone again. In the Docker Log, there's Error 25: Inappropriate ioctl for the device, what is that?

### Docker compose

services:
  macos:
    image: dockurr/macos
    container_name: macos
    restart: always
    environment:
      VERSION: big-sur
      DISK_SIZE: 64G
      RAM_SIZE: 4G
      CPU_CORES: 2
    volumes:
      - /DATA/AppData/macos/var/osx:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m

### Docker log

❯ Starting macOS for Docker v1.11...
❯ For support visit https://github.com/dockur/macos
❯ CPU: Intel Core TM i5 10210U CPU | RAM: 9/16 GB | DISK: 70 GB (ext4) | HOST: 6.1.0-25-amd64...

❯ Downloading macOS Big-sur recovery image...
Downloading 694-35959...
Saving http://oscdn.apple.com/content/downloads/41/28/071-71279/5djpevqmc2w0ti2c4n1m8mkz7fm791t1ic/RecoveryImage/BaseSystem.chunklist to /storage/tmp/BaseSystem.chunklist...
Traceback (most recent call last):
  File "/run/macrecovery.py", line 514, in <module>
    sys.exit(main())
             ^^^^^^
  File "/run/macrecovery.py", line 502, in main
    return action_download(args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/run/macrecovery.py", line 298, in action_download
    cnkpath = save_image(info[INFO_SIGN_LINK], info[INFO_SIGN_SESS], cnkname, args.outdir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/macrecovery.py", line 226, in save_image
    terminalsize = os.get_terminal_size().columns
                   ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 25] Inappropriate ioctl for device
❯ ERROR: Failed to fetch macOS "Big-sur" recovery image with board id "Mac-2BD1B31983FE1663"!

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/286259bf-3b77-47c5-8e40-87c191b9ff22)

**Comment by wronglylightcig** [comment]
fixed, i forgot the " on the environment
